### ISSUE TITLE
MediaCo application front end is getting crashed with main branch code in both embedded and portal modes

### ISSUE THREAD

**Issue by chaitanya-y** [pegasystems/react-sdk#323]
MediaCo application front end is getting crashed with MAIN branch code in both embedded and portal modes. Application is working properly in different branch.

1. Set up pega infinity server(8.7.0) and import mediaco application into infinity(sdk version is 8.7.0)
2. start the infinity server
3. git clone react-sdk from main branch & make necessary changes in sdk-config.json 
4. start the client server with npm run start-dev
5. Now, login with customer customer@mediaco username in embedded mode
6. Click on shop now on any of the services card. It is getting crashed and displaying 'Failed to display content. Contact the application administrator.'
7. check the console for the errors. api calls are getting successful.

**Expected behavior**
when user clicks on shop now. It should render the service request form.

**Screenshots**

![Screenshot (21)](https://user-images.githubusercontent.com/32432320/234772904-2cc4565d-da0c-4d00-bced-833f546968af.png)

![Screenshot (22)](https://user-images.githubusercontent.com/32432320/234772915-3801c957-7b29-43e8-9d9c-4e2d481e1fa5.png)

![Screenshot (23)](https://user-images.githubusercontent.com/32432320/234772928-28491dc3-6d2e-43d7-b050-ee5bfbca4a77.png)

![Screenshot (24)](https://user-images.githubusercontent.com/32432320/234772949-07860a8b-b27c-4d6e-9bb5-0bfbfdcb8b5d.png)

![Screenshot (25)](https://user-images.githubusercontent.com/32432320/234772962-1bd94f37-28cf-48d5-baa1-49238b00724d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Browser [e.g. chrome](Version 111.0.5563.149)

**Additional context**
Please add documentation for Constellatoin javascript public api's

**Comment by JEAxero** [comment]
Hi. Thanks for getting in touch about this issue.

You indicate that you see the failure in the main branch but not in another branch. Which branch works?

I ask because we made a significant change to the **main** on Monday and the main branch is now intended for Infinity 8.8.* and newer. For use on Infinity 8.7, you should use the new **release/8.8.10** branch. (Unfortunately, there's been a delay in updating the information on the Pega Marketplace site - https://community.pega.com/marketplace/components/react-sdk - which will make this more clear.)

I'll also mention that the SDK on 8.7.0 isn't an optimal use of the SDK. If you must use Infinity 8.7, we strongly recommend using 8.7.4 or 8.7.5. However, the ConstellationJS Engine and SDK experience has been significantly improved on Infinity 8.8.0+

One common thing to check is to make sure that your have updated your package.json to make sure you're using the correct version of the ConstellationJS Engine code. For Infinity 8.7.0, you should be sure that you package.json has the right dependency:

"@pega/constellationjs": "SDK-8.7.0"

And, as you change Infinity versions, you'll need to update this value to match the Infinity version you're targeting. And, of course, any time you change this value, you need to do an npm install or npm run build:dev:ci (where the ci means "clean and install) to get the right version included in your node_modules.

So, please take a look at these things and let us know the answers to these questions/observations and we'll see what the next step is. We'll follow this issue and help as we learn more about your specific environment/usage.

Thanks for your interest in the React SDK!

**Comment by chaitanya-y** [comment]
Hi JEAxero,

Thanks for the reply. I'm able to run the MediaCo app using the branch 'sharv/US-455605'. I'll try to setup with the branch release/8.8.10 and let you know.

**Comment by JEAxero** [comment]
> Thanks for the reply. I'm able to run the MediaCo app using the branch 'sharv/US-455605'. I'll try to setup with the branch release/8.8.10 and let you know.

Ok. Please let us know how that goes so we know what further assistance we can provide. Thanks!

**Comment by chaitanya-y** [comment]
Hi JEAxero, MediaCo app set up is done and working properly with react-sdk "Main" branch code. I've upgraded my infinity  to 8.8.2. I'll close this issue. Thank you.

**Comment by chaitanya-y** [comment]
Issue resolved
